### ISSUE TITLE
Login failed with SSL certificate verification error

### ISSUE THREAD

**Issue by KBOUSTM** [Nota-NetsPresso/netspresso-python#37] opened 2023-09-06 09:47 UTC
I'm trying to use the Netspresso Python client to log in to my account using the `SessionClient ` class, but I'm facing an SSL certificate verification error. Here are the details:

I'm using the latest version of the Netspresso Python client.
I'm using my Netspresso account email and password to log in.
I'm getting the following error message:

Login failed. Error: HTTPSConnectionPool(host='searcher.netspresso.ai', port=443): Max retries exceeded with url: /api/v1/auth/local/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

I believe this error is related to SSL certificate verification, but I'm not sure how to fix it. Can someone from the Netspresso team help me troubleshoot this issue?

Thanks in advance for your help!

**Comment by SanggeonPark** [comment] 2023-09-06 13:47
Hello!!

I am Sanggeon form NetsPresso team.
Can I get your python environment informations?
Please run the following commands and provide me the output.

```
python3 -V
python3 -m certifi
python3 -m pip list
```

According to the provided information, I think I am going to close to solve this issue ;)

Thanks!!

Sanggeon

**Comment by KBOUSTM** [comment] 2023-09-06 14:13
Hi Sanggeon,

Thank you for getting back to me and offering to help with the SSL certificate verification error. Here's the output of the commands you requested:

```Bash
python -V
Python 3.9.13

python -m certifi
user\compression_venv\lib\site-packages\certifi\cacert.pem


python -m pip list
Package                      Version
---------------------------- ------------
absl-py                      1.4.0
alembic                      1.12.0
antlr4-python3-runtime       4.9.3
appdirs                      1.4.4
asttokens                    2.2.1
astunparse                   1.6.3
audioread                    3.0.0
backcall                     0.2.0
blinker                      1.6.2
cachetools                   5.3.1
certifi                      2023.7.22
cffi                         1.15.1
charset-normalizer           3.2.0
click                        8.1.7
cloudpickle                  2.2.1
cmaes                        0.10.0
colorama                     0.4.5
coloredlogs                  15.0.1
colorlog                     6.7.0
comm                         0.1.4
contourpy                    1.1.0
cycler                       0.11.0
databricks-cli               0.17.7
debugpy                      1.6.7.post1
decorator                    5.1.1
dnspython                    2.4.2
docker                       6.1.3
email-validator              2.0.0
entrypoints                  0.4
executing                    1.2.0
Flask                        2.3.3
flatbuffers                  23.5.26
fonttools                    4.42.1
gast                         0.5.4
gitdb                        4.0.10
GitPython                    3.1.34
google-auth                  2.22.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
greenlet                     2.0.2
grpcio                       1.57.0
h5py                         3.9.0
humanfriendly                10.0
hydra-core                   1.3.2
idna                         3.4
imageio                      2.31.3
imgaug                       0.4.0
importlib-metadata           6.8.0
ipykernel                    6.25.1
ipython                      8.14.0
itsdangerous                 2.1.2
jedi                         0.19.0
Jinja2                       3.1.2
joblib                       1.2.0
jupyter_client               8.3.0
jupyter_core                 5.3.1
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.5
lazy_loader                  0.3
libclang                     16.0.6
librosa                      0.10.0.post2
llvmlite                     0.40.1
loguru                       0.7.0
Mako                         1.2.4
Markdown                     3.4.4
MarkupSafe                   2.1.3
matplotlib                   3.6.2
matplotlib-inline            0.1.6
mlflow                       2.3.0
mpmath                       1.3.0
msgpack                      1.0.5
munch                        2.5.0
nest-asyncio                 1.5.7
netspresso                   1.1.6
networkx                     3.1
numba                        0.57.1
numpy                        1.23.4
oauthlib                     3.2.2
omegaconf                    2.3.0
onnx                         1.12.0
onnxconverter-common         1.13.0
onnxruntime                  1.14.1
opencv-python                4.6.0.66
opt-einsum                   3.3.0
optuna                       3.1.1
packaging                    23.1
pandas                       1.5.3
parso                        0.8.3
pickleshare                  0.7.5
Pillow                       10.0.0
pip                          22.0.4
platformdirs                 3.10.0
pooch                        1.6.0
prompt-toolkit               3.0.39
protobuf                     3.19.6
psutil                       5.9.5
pure-eval                    0.2.2
pyarrow                      11.0.0
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     1.10.4
Pygments                     2.16.1
PyJWT                        2.7.0
pyparsing                    3.1.1
pyreadline3                  3.4.1
pyserial                     3.5
python-dateutil              2.8.2
pytz                         2023.3
PyWavelets                   1.4.1
pywin32                      306
PyYAML                       6.0.1
pyzmq                        25.1.1
querystring-parser           1.2.4
requests                     2.30.0
requests-oauthlib            1.3.1
rsa                          4.9
scikit-image                 0.21.0
scikit-learn                 1.2.2
scipy                        1.11.2
seaborn                      0.12.2
setuptools                   58.1.0
shapely                      2.0.1
six                          1.16.0
skl2onnx                     1.14.0
smmap                        5.0.0
soundfile                    0.12.1
soxr                         0.3.6
SQLAlchemy                   2.0.20
sqlparse                     0.4.4
stack-data                   0.6.2
sympy                        1.12
tabulate                     0.9.0
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.3
tensorflow-estimator         2.8.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
threadpoolctl                3.2.0
tifffile                     2023.8.30
tornado                      6.3.3
tqdm                         4.65.0
traitlets                    5.9.0
typing_extensions            4.5.0
urllib3                      1.26.16
waitress                     2.1.2
wcwidth                      0.2.6
websocket-client             1.6.2
Werkzeug                     2.3.7
wget                         3.2
wheel                        0.41.2
win32-setctime               1.1.0
wrapt                        1.15.0
zipp                         3.16.2 
---------------------------- ------------

```
I hope this information helps you understand my Python environment better. Please let me know if there's anything else you need from me to resolve this issue.

Thank you for your help :) 

Khaoula

**Comment by SanggeonPark** [comment] 2023-09-06 15:11
Hi Khaoula!

One more information I need to reproduce the issue ;)
Are you working on Linux or Windows?
Can you share me your operating system and its versions?

And one more thing!! if you are running it on a docker container, can you also share the information?

Thank you.

Sanggeon

**Comment by SanggeonPark** [comment] 2023-09-07 05:29
Hi Khaoula!!

Can you please run the following code before you create SessionClient Instance?

```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```

I hope this helps you!!

Thank you.

Sanggeon

**Comment by KBOUSTM** [comment] 2023-09-07 07:53
Hi Sanggeon,

I'm using a Windows machine with version 21H2, and I'm not running the code in a Docker container but in a notebook. 

Thank you for your suggestion to modify the SSL context. I tried running the code you provided before creating the SessionClient instance, but unfortunately, it did not resolve the SSL certificate verification error. Here's the error message I'm seeing:

``````bash
Login failed. Error: HTTPSConnectionPool(host='searcher.netspresso.ai', port=443): Max retries exceeded with url: /api/v1/auth/local/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
``````
Please let me know if there's anything else you suggest I try, or if there's any additional information, I can provide to help resolve this issue.

Thank you for your assistance.

Khaoula

**Comment by SanggeonPark** [comment] 2023-09-07 12:36
Hi Khaoula,

I tried to reproduce the same issue what you are facing now, unfortunately I failed to reproduce it.
If it doesn't bother you can you please run the following code again?
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

from netspresso.client import SessionClient
EMAIL = "Your Email"
PASSWORD = "Your Password"
session = SessionClient(email=EMAIL, password=PASSWORD)
```

Because I found a missing part from your certifi .pem file path
```
user\compression_venv\lib\site-packages\certifi\cacert.pem
```
Usually it contains the python version int the path like the following.
```
/usr/local/lib/python3.10/dist-packages/certifi/cacert.pem
````

And I am sharing the notebook which is working with NetsPresso Python Package.
Can you please try it out?
[PyNetsPresso_Session_Test.ipynb](https://colab.research.google.com/drive/19dqou5JEODLeR7WZT18Y8jy30AvAV36u?usp=sharing)

Thank you.

Sanggeon

**Comment by SanggeonPark** [comment] 2023-09-11 11:42
Hi Khaoula(@KBOUSTM ),

I hope you are doing well,
If you still have the same issue, please set up a new Python environment and try it on your local machine instead of in a notebook.

Can you try it and share the result with me?

Thank you.

Sanggeon

**Comment by KBOUSTM** [comment] 2023-09-28 08:51
Hello SanggeonPark, 

I apologize for the delayed response. Thank you for your suggestion. 
I tried it with the equivalent Windows commands, and I would like to mention that I am working under a proxy and have set the proxy parameters like the following code: 
```bash
import os
os.environ['http_proxy'] = "http://user:passwd@ip_address:port"
os.environ['https_proxy'] = "http://user:passwd@ip_address:port"
os.environ['NO_SSL_VERIFY'] = "1". 
```
And i still have the same issue. 

Please let me know if you have any further suggestions or if there is any additional information, I can provide to help resolve this issue.

Thank you again for your time and assistance.

Best regards, 
Khaoula

**Comment by SanggeonPark** [comment] 2023-10-11 13:48
Hi Khaoula,

Sorry for my late response.
I am going to check with new proxy setting and get back to you.

Thank you

Best regards,
Sanggeon

**Comment by SanggeonPark** [comment] 2023-10-12 13:12
Hi Khaoula,

Can you please put the following codes on the top of your main python file?
This code will replace all the functions from requests api module and disable the server certificate verification.
The following codes have to be called before you import any modules of NetsPresso package.
It will show you some warnings for insecure server certificate verification.
In my personal opinion, it's not a nice way to solve this issue.
I will get back to you later if I find any other better solution.


```
import requests

def new_get(url, params=None, **kwargs):
    kwargs.setdefault('verify', False)
    return requests.request("get", url, params=params, **kwargs)

def new_post(url, params=None, **kwargs):
    kwargs.setdefault('verify', False)
    return requests.request("post", url, params=params, **kwargs)

def new_options(url, **kwargs):
    kwargs.setdefault('verify', False)
    return requests.request("options", url, **kwargs)

def new_head(url, **kwargs):
    kwargs.setdefault('verify', False)
    kwargs.setdefault("allow_redirects", False)
    return requests.request("head", url, **kwargs)

def new_put(url, data=None, **kwargs):
    kwargs.setdefault('verify', False)
    return requests.request("put", url, data=data, **kwargs)

def new_patch(url, data=None, **kwargs):
    kwargs.setdefault('verify', False)
    return requests.request("patch", url, data=data, **kwargs)

def new_delete(url, **kwargs):
    print("new_delete")
    kwargs.setdefault('verify', False)
    return requests.request("delete", url, **kwargs)

def swap_requests_functions():
    requests.get = new_get
    requests.post = new_post
    requests.options = new_options
    requests.head = new_head
    requests.put = new_put
    requests.patch = new_patch
    requests.delete = new_delete

swap_requests_functions()

from netspresso.compressor import (
    ModelCompressor,
    Task,
    Framework,
    CompressionMethod,
    Policy,
    LayerNorm,
    GroupPolicy,
    Options,
)

from netspresso.client import SessionClient
from netspresso.launcher import ModelConverter, ModelBenchmarker, ModelFramework, DeviceName, BenchmarkTask, ConversionTask, Model
```

Best regards,
Sanggeon

**Comment by KBOUSTM** [comment] 2023-10-13 12:05
Hello Sanggeon Park,

This trick worked for me. Shall we keep the issue open until we find a better solution? 
Thank you so much for your collaboration.

Best Regards, 
Khaoula

**Comment by SanggeonPark** [comment] 2023-10-16 13:37
Hi Khaoula!

Great to hear that you can now use it!
I will keep this issue. And get back to you with another better solution !!

Thank you.

Best Regards,
Sanggeon

**Comment by Only-bottle** [comment] 2023-12-20 06:43
The issue has been confirmed to be resolved, so I will close it.

**Closed as completed by Only-bottle** 2023-12-20 06:43 UTC
